# Generated by Django 2.2 on 2019-05-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vaccionations',
            new_name='vaccinations',
        ),
    ]
