# Generated by Django 2.2 on 2019-05-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20190505_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(),
        ),
    ]
